### PR TITLE
Update for Sublime Text 3 + Cleanup

### PR DESCRIPTION
**Pull request by the0neyouseek**
Cleaned up some code and updated for Sublime Text 3.

### CODE REVIEW

**Comment by timnevits** [comment]
Thanks much for this -- I'm finally able to upgrade to ST 3 now.

**Comment by the0neyouseek** [comment]
No problem.

**Comment by loenze** [comment]
Thank you! :)

**Comment by djwaix** [comment]
Brilliant!
Thank you for doing this!!

**Comment by ProLoser** [comment]
+1

**Pull request merged**
